Repository halo-sigs/plugin-oauth2, pull requests merged in 2023-03, with the labels that each got.

#1 feat: github oauth authentication is supported
  README.md
  build.gradle
  lib/halo-2.0.0-SNAPSHOT-plain.jar
  lib/halo-2.4.0-SNAPSHOT-plain.jar
  settings.gradle
  src/main/java/run/halo/oauth/AuthorizedClient.java
  src/main/java/run/halo/oauth/DefaultOAuth2AuthorizedClientService.java
  src/main/java/run/halo/oauth/DefaultSocialUserDetailsService.java
  src/main/java/run/halo/oauth/DefaultUserDetailsService.java
  src/main/java/run/halo/oauth/GithubUserProfileMapper.java
  src/main/java/run/halo/oauth/ListedConnection.java
  src/main/java/run/halo/oauth/Oauth2Authenticator.java
  src/main/java/run/halo/oauth/Oauth2AuthorizationRequestRedirectWebFilter.java
  src/main/java/run/halo/oauth/Oauth2LoginConfiguration.java
  src/main/java/run/halo/oauth/Oauth2UserProfile.java
  src/main/java/run/halo/oauth/Oauth2UserProfileMapper.java
  src/main/java/run/halo/oauth/Oauth2UserProfileMapperManager.java
  src/main/java/run/halo/oauth/OauthClientRegistrationRepository.java
  src/main/java/run/halo/oauth/OauthGithubConfig.java
  src/main/java/run/halo/oauth/OauthGithubPlugin.java
  src/main/java/run/halo/oauth/SocialServerOauth2AuthorizationRequestResolver.java
  src/main/java/run/halo/oauth/SocialUserDetailsService.java
  src/main/java/run/halo/oauth/UserConnectionEndpoint.java
  src/main/java/run/halo/oauth/UserConnectionService.java
  src/main/java/run/halo/oauth/UserConnectionServiceImpl.java
  src/main/java/run/halo/starter/StarterPlugin.java
  src/main/resources/extensions/auth-provider.yaml
  src/main/resources/extensions/extension-definitions.yaml
  src/main/resources/extensions/setting.yaml
  src/main/resources/logo.svg
  src/main/resources/plugin.yaml
  src/test/java/run/halo/oauth/DefaultSocialUserDetailsServiceTest.java
  src/test/java/run/halo/oauth/GithubUserProfileMapperTest.java
  src/test/java/run/halo/oauth/ListedConnectionTest.java
  src/test/java/run/halo/oauth/Oauth2LoginConfigurationTest.java
  src/test/java/run/halo/oauth/OauthClientRegistrationRepositoryTest.java
  src/test/java/run/halo/oauth/UserConnectionServiceImplTest.java
Labels: release-note

#3 feat: add github/gitee/gitlab oauth2 supports
  README.md
  build.gradle
  console/vite.config.ts
  lib/halo-2.0.0-SNAPSHOT-plain.jar
  lib/halo-2.4.0-SNAPSHOT-plain.jar
  settings.gradle
  src/main/java/run/halo/oauth/AuthorizedClient.java
  src/main/java/run/halo/oauth/DefaultOAuth2AuthorizedClientService.java
  src/main/java/run/halo/oauth/DefaultSocialUserDetailsService.java
  src/main/java/run/halo/oauth/DefaultUserDetailsService.java
  src/main/java/run/halo/oauth/GenericUserProfileMapper.java
  src/main/java/run/halo/oauth/ListedConnection.java
  src/main/java/run/halo/oauth/Oauth2Authenticator.java
  src/main/java/run/halo/oauth/Oauth2AuthorizationRequestRedirectWebFilter.java
  src/main/java/run/halo/oauth/Oauth2ClientRegistration.java
  src/main/java/run/halo/oauth/Oauth2LoginConfiguration.java
  src/main/java/run/halo/oauth/Oauth2UserProfile.java
  src/main/java/run/halo/oauth/Oauth2UserProfileMapper.java
  src/main/java/run/halo/oauth/Oauth2UserProfileMapperManager.java
  src/main/java/run/halo/oauth/OauthClientRegistrationRepository.java
  src/main/java/run/halo/oauth/OauthGithubConfig.java
  src/main/java/run/halo/oauth/OauthGithubPlugin.java
  src/main/java/run/halo/oauth/SocialServerOauth2AuthorizationRequestResolver.java
  src/main/java/run/halo/oauth/SocialUserDetailsService.java
  src/main/java/run/halo/oauth/UserConnectionEndpoint.java
  src/main/java/run/halo/oauth/UserConnectionService.java
  src/main/java/run/halo/oauth/UserConnectionServiceImpl.java
  src/main/java/run/halo/starter/StarterPlugin.java
  src/main/resources/console/main.js
  src/main/resources/extensions/auth-provider.yaml
  src/main/resources/extensions/client-registrations.yaml
  src/main/resources/extensions/extension-definitions.yaml
  src/main/resources/extensions/reverseproxy.yaml
  src/main/resources/extensions/role.yaml
  src/main/resources/extensions/setting.yaml
  src/main/resources/logo.svg
  src/main/resources/plugin.yaml
  src/main/resources/static/gitee.svg
  src/main/resources/static/github.svg
  src/main/resources/static/gitlab.svg
  src/test/java/run/halo/oauth/DefaultSocialUserDetailsServiceTest.java
  src/test/java/run/halo/oauth/GithubUserProfileMapperTest.java
  src/test/java/run/halo/oauth/ListedConnectionTest.java
  src/test/java/run/halo/oauth/Oauth2LoginConfigurationTest.java
  src/test/java/run/halo/oauth/OauthClientRegistrationRepositoryTest.java
  src/test/java/run/halo/oauth/UserConnectionServiceImplTest.java
Labels: release-note, lgtm, approved

#6 docs: update readme
  README.md
Labels: release-note-none, kind/documentation, lgtm, approved

#7 feat: support redirect to binding
  src/main/java/run/halo/oauth/Oauth2Authenticator.java
  src/main/java/run/halo/oauth/UserConnectionService.java
  src/main/java/run/halo/oauth/UserConnectionServiceImpl.java
Labels: release-note, lgtm, approved

#9 fix: user connections was not completely deleted when unbinding
  src/main/java/run/halo/oauth/UserConnectionEndpoint.java
  src/main/java/run/halo/oauth/UserConnectionService.java
  src/main/java/run/halo/oauth/UserConnectionServiceImpl.java
Labels: release-note, lgtm, approved

#10 release: 1.0.0
  build.gradle
  src/main/resources/plugin.yaml
Labels: release-note-none, lgtm, approved
