Repository halo-sigs/plugin-oauth2, pull requests merged in 2024-10, with the labels that each got.

#64 Refactor OAuth2 login for Halo 2.20
  build.gradle
  src/main/java/run/halo/oauth/DefaultOAuth2AuthorizedClientService.java
  src/main/java/run/halo/oauth/DefaultSocialUserDetailsService.java
  src/main/java/run/halo/oauth/DefaultUserDetailsService.java
  src/main/java/run/halo/oauth/HaloOAuth2AuthenticationWebFilter.java
  src/main/java/run/halo/oauth/HaloOAuth2RedirectWebFilter.java
  src/main/java/run/halo/oauth/ListedConnection.java
  src/main/java/run/halo/oauth/Oauth2Authenticator.java
  src/main/java/run/halo/oauth/Oauth2AuthorizationRequestRedirectWebFilter.java
  src/main/java/run/halo/oauth/Oauth2LoginConfiguration.java
  src/main/java/run/halo/oauth/SocialUserDetailsService.java
  src/main/java/run/halo/oauth/UserConnectionDisconnectedListener.java
  src/main/java/run/halo/oauth/UserConnectionEndpoint.java
  src/main/java/run/halo/oauth/UserConnectionService.java
  src/main/java/run/halo/oauth/UserConnectionServiceImpl.java
  src/main/resources/extensions/auth-provider.yaml
  src/main/resources/plugin.yaml
  src/test/java/run/halo/oauth/DefaultSocialUserDetailsServiceTest.java
  src/test/java/run/halo/oauth/ListedConnectionTest.java
  src/test/java/run/halo/oauth/UserConnectionServiceImplTest.java
Labels: release-note-none, lgtm, approved

#65 feat: add authType for authproviders
  src/main/resources/extensions/auth-provider.yaml
Labels: release-note, lgtm, approved

#66 Fix the problem of NoSuchMethod error of auth provider
  src/main/java/run/halo/oauth/OauthClientRegistrationRepository.java
  src/test/java/run/halo/oauth/OauthClientRegistrationRepositoryTest.java
Labels: kind/bug, release-note, lgtm, approved

#74 Resolve baseUrl in redirect URI with external URL
  src/main/java/run/halo/oauth/Oauth2LoginConfiguration.java
  src/main/java/run/halo/oauth/OauthClientRegistrationRepository.java
  src/test/java/run/halo/oauth/Oauth2LoginConfigurationTest.java
  src/test/java/run/halo/oauth/OauthClientRegistrationRepositoryTest.java
Labels: kind/improvement, release-note, lgtm, approved

#71 Support OIDC protocol
  src/main/java/run/halo/oauth/HaloOAuth2AuthenticationWebFilter.java
Labels: kind/feature, release-note, lgtm, approved
